source 'https://rubygems.org'

gem 'dotenv'
gem 'rspec'
gem 'kommando', '~> 0.1.2'
gem 'rake'

group :development do
  gem 'pry', :require => true
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'krates', path: '../cli'
  gem 'pry', :require => true
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
end

