#!/usr/bin/env bash

# This file exists mostly for backwards dependency to
# allow the old "which krates && . foofoo/init"
# completion loading
_krates_complete() {
  COMPREPLY=()
  local word="${COMP_WORDS[COMP_CWORD]}"
  local completions="$(krates complete ${COMP_WORDS[*]})"
  COMPREPLY=( $(compgen -W "$completions" -- "$word") )
}

if [ "$ZSH_VERSION" != "" ]; then
  autoload -U +X compinit && compinit
  autoload -U +X bashcompinit && bashcompinit
fi

which krates > /dev/null && complete -F _krates_complete krates
