source 'https://rubygems.org'

gemspec

group :test do
  gem "rspec"
  gem "krates-plugin-hello", path: "./examples/krates-plugin-hello"
  gem 'simplecov', :require => false, :group => :test
  gem 'webmock', '~> 3.0', require: false
end

group :development do
  gem 'pry'
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
end
