pipeline {

  agent {
    node {
      label 'local'
    }
  }

  stages {
    stage('Setup') {
      steps {
        dir 'cli' {
          sh 'make build'
          sh 'make volume-init'
          sh 'make up'
        }
      }
    }

    stage('Test') {
      steps {
        dir 'cli' {
          sh 'make test'
        }
      }
    }

    stage('Publish') {
      when {
        branch 'master'
        buildingTag()
        expression { currentBuild.result == null || currentBuild.result == 'SUCCESS' }
      }
      steps {
        dir 'cli' {
          sh 'make gemspec'
          sh 'make credspec'
          sh 'make publish'
        }
      }
    }
  }

  post {
    always {
      dir 'cli' { sh 'make teardown' }
    }
  }
}