pipeline {

  agent any

  options {
    buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')
  }

  stages {
    stage('Setup') {
      steps {
        dir('cli') {
          sh 'make build'
          sh 'make volume-init'
          sh 'make up'
        }
      }
    }

    stage('Test') {
      steps {
        dir('cli') {
          sh 'make test'
        }
      }
    }

    stage('Publish') {
      when {
        branch 'master'
        tag pattern: 'v*'
        expression { currentBuild.result == null || currentBuild.result == 'SUCCESS' }
      }
      steps {
        dir('cli') {
          sh 'make gemspec'
          sh 'make credspec'
          sh 'make publish'
        }
      }
    }
  }

  post {
    always {
      dir('cli') { sh 'make teardown' }
    }
  }
}