source 'https://rubygems.org'

gem 'kontena-websocket-client'
gem 'docker-api'
gem 'msgpack'
gem 'activesupport'
gem 'celluloid'
gem 'etcd'
gem 'statsd-ruby'
gem 'vmstat'
gem 'fluent-logger'
gem 'rbtrace', require: false

group :development, :test do
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'dotenv', require: false
  gem 'webmock', require: false
  gem 'simplecov', require: false
  gem 'ruby-prof', require: false
  gem 'pry'
  gem 'pry-rescue'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-stack_explorer'
end
